### ISSUE TITLE
Right-click on the Hierarchy and go to AR+GPS -> Create Basic Scene Structure issue.

### ISSUE THREAD

**Issue by madhugk** [dmbfm/unity-ar-gps-location-issues#28] opened 2020-01-20 11:23 UTC
Unity Editor is not showing up AR+GPS in the dropdown when I followed the steps in the guide by importing packages and deleting mainCamera, Right click on the Hierarchy it is not showing AR+GPS option. 

![Screenshot 2020-01-20 at 11 21 21](https://user-images.githubusercontent.com/48920986/72722752-ff157f00-3b76-11ea-9804-5bd96b50072f.png)

 - OS: MacOS
 - Unity Version: I tried all available versions from 2019.2.(11,12,13,14,15,17). 

Please help me on this. I am beginner to Unity and AR technology.

**Comment by dmbfm** [comment] 2020-01-20 13:22
Are there any errors showing on the Unity console?

**Comment by dmbfm** [comment] 2020-01-20 13:22
Which version of the AR+GPS location asset are you using?

**Comment by madhugk** [comment] 2020-01-20 13:27
It's showing the below warning: 

Cannot resolve parent rule: .ToolbarPopup
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/builduser/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)

**Comment by madhugk** [comment] 2020-01-20 13:28
I am using the latest asset as I updated today morning.

**Comment by dmbfm** [comment] 2020-01-20 18:40
We tested on 2019.2, both on windows and mac, importing the AR+GPS plugin in a new project, and could not reproduce this error. 

Does this happen with an empty project, or are there more assets imported in it?

**Comment by madhugk** [comment] 2020-01-21 15:39
this is an empty project with no other assets. I tried to resolve by setting up in another iMac and it started to work even with the latest 2019.2.18 and I see the both MacOS are the same(10.15.2) not sure what's causing the issue.

**Comment by dmbfm** [comment] 2020-01-21 16:20
That is weird. In any case the menu is more of a convenience, you can set everything up without it. 

Closing the issue for now, thanks!

**Closed by dmbfm** 2020-01-21 16:20 UTC
